pollequiz/quiz/urls.py
from django.urls import path
from pollequiz.quiz import views


app_name = 'quiz'
urlpatterns = [
    path('', views.quiz.QuizListView.as_view(), name='list_all'),
    path('my/', views.quiz.MyQuizListView.as_view(), name='list_my'),
    path('<int:quiz_id>/', views.question.QuestionsListView.as_view(), name='quiz_card'),
    path('new/', views.quiz.QuizCreateView.as_view(), name='new'),
    path('<int:pk>/edit/', views.quiz.QuizUpdateView.as_view(), name='quiz_update'),
    path('<int:pk>/delete/', views.quiz.QuizDeleteView.as_view(), name='quiz_delete'),
    path('<int:quiz_id>/new/', views.question.QuestionCreateView.as_view(), name='question_new'),
    path('<int:quiz_id>/<int:pk>/edit/', views.question.QuestionUpdateView.as_view(), name='question_update'),
    path('<int:quiz_id>/<int:pk>/delete/', views.question.QuestionDeleteView.as_view(), name='question_delete'),
    path('<int:quiz_id>/<int:q_id>/', views.answer.AnswerListView.as_view(), name='question_card'),
    path('<int:quiz_id>/<int:q_id>/new/', views.answer.AnswerCreateView.as_view(), name='answer_new'),
    path('<int:quiz_id>/<int:q_id>/<int:pk>/edit/', views.answer.AnswerUpdateView.as_view(), name='answer_update'),
    path('<int:quiz_id>/<int:q_id>/<int:pk>/delete/', views.answer.AnswerDeleteView.as_view(), name='answer_delete'),
]

pollequiz/run/urls.py
from django.urls import path
from pollequiz.run.views import views, auth_views


app_name = 'run'
urlpatterns = [
    path('', views.QuizListView.as_view(), name='quiz_list'),
    path('<int:quiz_id>/', views.TakeFirstPage.as_view(), name='quiz_start'),
    path('<int:quiz_id>/<int:pk>/<int:q_id>', views.TakeQuestion.as_view(), name='quiz_take'),
    path('result/<int:pk>/', views.QuizResult.as_view(), name='quiz_result'),
    path('takes/<int:quiz_id>/', auth_views.ResultsListForAuthors.as_view(), name='takes_list'),
    path('takes/detail/<int:pk>/', auth_views.ResultsForAuthors.as_view(), name='takes_detail'),
]

pollequiz/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, HelpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', HomeView.as_view(), name='home'),
    path('help/', HelpView.as_view(), name='help'),
    path('account/', include('pollequiz.users.urls')),
    path('api/', include('pollequiz.api.urls')),
    path('quiz/', include('pollequiz.quiz.urls')),
    path('test/', include('pollequiz.run.urls')),
]

pollequiz/quiz/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext as _
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.utils import timezone


# Create your models here.
class Quiz(models.Model):
    name = models.CharField(max_length=100, blank=False, verbose_name=_('Quiz name'))
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name=_('Created by'))
    is_poll = models.BooleanField(default=False, verbose_name=_('It\'s a poll (no points for questions)'))
    description = models.TextField(blank=True, verbose_name=_('Description (optional)'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('Created at'))
    modified_at = models.DateTimeField(auto_now=True, verbose_name=_('Last modified'))

    def get_questions_list(self):
        return list(Question.objects.filter(quiz=self.id).order_by('q_number'))


class Question(models.Model):

    TYPES = (
        ('sing', _('Single choice')),
        ('mult', _('Multiple choice')),
        # ('open', _('Open ended')),
    )

    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, verbose_name=_('Quiz'))
    q_number = models.IntegerField(verbose_name=_('Question number'))
    q_type = models.CharField(choices=TYPES, max_length=4)
    text = models.TextField()
    points = models.IntegerField(default=0, verbose_name=_('Points for correct answer'))
    ordering = ['q_number']

    def get_answers_list(self):
        return list(Answer.objects.filter(question=self.id).order_by('a_number'))


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name=_('Question'))
    a_number = models.IntegerField(verbose_name=_('Answer number'))
    text = models.TextField()
    correct = models.BooleanField(default=False, verbose_name=_('This answer is correct'))
    ordering = ['a_number']


@receiver(post_save, sender=Question)
def question_save_handler(instance, *args, **kwargs):
    quiz = instance.quiz
    quiz.modified_at = timezone.now()
    quiz.save()


@receiver(post_save, sender=Answer)
def answer_save_handler(instance, *args, **kwargs):
    quiz = instance.question.quiz
    quiz.modified_at = timezone.now()
    quiz.save()

pollequiz/quiz/forms.py
from django import forms
from pollequiz.quiz.models import Quiz, Question, Answer


class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = [
            'name',
            'is_poll',
            'description',
        ]


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = [
            'q_number',
            'q_type',
            'text',
            'points',
        ]


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = [
            'a_number',
            'text',
            'correct',
        ]

pollequiz/quiz/views.py
from django.views.generic.detail import DetailView
# from django.views.generic.list import ListView
from django_filters.views import FilterView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from pollequiz.quiz.models import Quiz
from pollequiz.quiz.forms import QuizForm
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
import pollequiz.pq_objects as pq_objects
import pollequiz.text_constants as txt
from .filter import QuizFilter, MyQuizFilter

User = get_user_model()


# Create your views here.
class QuizDetailView(LoginRequiredMixin, DetailView):
    model = Quiz
    template_name = "quiz/quiz_card.html"
    context_object_name = 'quiz'
    redirect_url = reverse_lazy('users:login')


class QuizListView(pq_objects.FailedAccessMixin, pq_objects.PQFormContextMixin, LoginRequiredMixin, FilterView):
    model = Quiz
    filterset_class = QuizFilter
    ordering = ['id']
    redirect_url = reverse_lazy('users:login')
    template_name = 'quiz/list.html'
    context_object_name = 'objects'
    btn_text = txt.FILTER_BTN


class MyQuizListView(QuizListView):
    filterset_class = MyQuizFilter

    def get_queryset(self):
        queryset = super().get_queryset().filter(author=self.request.user.id)
        return queryset


class QuizCreateView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    CreateView
):
    model = Quiz
    form_class = QuizForm
    template_name = 'quiz/quiz_form.html'
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('users:login')
    title_text = txt.CREATE_QUIZ_TITLE
    btn_text = txt.CREATE_BTN

    def get_success_url(self):
        return reverse_lazy('quiz:quiz_card', kwargs={'pk': self.object.id})

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super().form_valid(form)


class QuizUpdateView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    UserPassesTestMixin,
    UpdateView
):
    model = Quiz
    form_class = QuizForm
    template_name = 'quiz/quiz_form.html'
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('users:login')
    title_text = txt.UPDATE_QUIZ_TITLE
    btn_text = txt.UPDATE_BTN

    def test_func(self):
        return self.request.user == self.get_object().author


class QuizDeleteView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    UserPassesTestMixin,
    DeleteView
):
    model = Quiz
    template_name = "quiz/delete.html"
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('quiz:list_my')
    title_text = txt.DELETE_QUIZ_TITLE
    btn_text = txt.DELETE_BTN

    def test_func(self):
        return self.request.user == self.get_object().author

pollequiz/quiz/views/answer.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from pollequiz.quiz.models import Quiz, Question, Answer
from pollequiz.quiz.forms import AnswerForm
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
import pollequiz.pq_objects as pq_objects
import pollequiz.text_constants as txt

User = get_user_model()


class AnswerListView(pq_objects.FailedAccessMixin, pq_objects.PQQuerySetMixin, LoginRequiredMixin, ListView):
    model = Answer
    ordering = ['a_number']
    redirect_url = reverse_lazy('users:login')
    template_name = 'quiz/quiz_answers.html'
    context_object_name = 'objects'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.kwargs.get('quiz_id'):
            context['quiz'] = Quiz.objects.get(id=self.kwargs['quiz_id'])
        if self.kwargs.get('q_id'):
            context['question'] = Question.objects.get(id=self.kwargs['q_id'])
        return context


class AnswerCreateView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    pq_objects.PQSuccessRedirectMixin,
    CreateView
):
    model = Answer
    form_class = AnswerForm
    template_name = 'quiz/quiz_form.html'
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('users:login')
    title_text = txt.CREATE_ANSWER_TITLE
    btn_text = txt.CREATE_BTN

    def form_valid(self, form):
        form.instance.question_id = self.kwargs['q_id']
        return super().form_valid(form)


class AnswerUpdateView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    pq_objects.PQUserTestMixin,
    pq_objects.PQSuccessRedirectMixin,
    UpdateView
):
    model = Answer
    form_class = AnswerForm
    template_name = 'quiz/quiz_form.html'
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('users:login')
    title_text = txt.UPDATE_ANSWER_TITLE
    btn_text = txt.UPDATE_BTN


class AnswerDeleteView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    pq_objects.PQUserTestMixin,
    pq_objects.PQSuccessRedirectMixin,
    DeleteView
):
    model = Answer
    template_name = "quiz/delete.html"
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('quiz:list_my')
    title_text = txt.DELETE_ANSWER_TITLE
    btn_text = txt.DELETE_BTN

pollequiz/quiz/views/question.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from pollequiz.quiz.models import Quiz, Question
from pollequiz.quiz.forms import QuestionForm
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
import pollequiz.pq_objects as pq_objects
import pollequiz.text_constants as txt

User = get_user_model()


class QuestionsListView(pq_objects.FailedAccessMixin, pq_objects.PQQuerySetMixin, LoginRequiredMixin, ListView):
    model = Question
    ordering = ['q_number']
    redirect_url = reverse_lazy('users:login')
    template_name = 'quiz/quiz_questions.html'
    context_object_name = 'objects'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.kwargs.get('quiz_id'):
            context['quiz'] = Quiz.objects.get(id=self.kwargs['quiz_id'])
        return context


class QuestionCreateView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    CreateView
):
    model = Question
    form_class = QuestionForm
    template_name = 'quiz/quiz_form.html'
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('users:login')
    title_text = txt.CREATE_QUESTION_TITLE
    btn_text = txt.CREATE_BTN

    def get_success_url(self):
        return reverse_lazy('quiz:quiz_card', kwargs={'quiz_id': self.object.quiz.id})

    def form_valid(self, form):
        form.instance.quiz_id = self.kwargs['quiz_id']
        return super().form_valid(form)


class QuestionUpdateView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    pq_objects.PQUserTestMixin,
    UpdateView
):
    model = Question
    form_class = QuestionForm
    template_name = 'quiz/quiz_form.html'
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('users:login')
    title_text = txt.UPDATE_QUESTION_TITLE
    btn_text = txt.UPDATE_BTN

    def get_success_url(self):
        return reverse_lazy('quiz:quiz_card', kwargs={'quiz_id': self.object.quiz.id})


class QuestionDeleteView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    pq_objects.PQUserTestMixin,
    DeleteView
):
    model = Question
    template_name = "quiz/delete.html"
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('quiz:list_my')
    title_text = txt.DELETE_QUESTION_TITLE
    btn_text = txt.DELETE_BTN

    def get_success_url(self):
        return reverse_lazy('quiz:quiz_card', kwargs={'quiz_id': self.object.quiz.id})

pollequiz/quiz/views/quiz.py
# from django.views.generic.detail import DetailView
from django_filters.views import FilterView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from pollequiz.quiz.models import Quiz
from pollequiz.quiz.forms import QuizForm
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
import pollequiz.pq_objects as pq_objects
import pollequiz.text_constants as txt
from pollequiz.quiz.filter import QuizFilter, MyQuizFilter

User = get_user_model()


class QuizListView(pq_objects.FailedAccessMixin, pq_objects.PQFormContextMixin, LoginRequiredMixin, FilterView):
    model = Quiz
    filterset_class = QuizFilter
    ordering = ['-modified_at']
    redirect_url = reverse_lazy('users:login')
    template_name = 'quiz/list.html'
    context_object_name = 'objects'
    btn_text = txt.FILTER_BTN


class MyQuizListView(QuizListView):
    filterset_class = MyQuizFilter

    def get_queryset(self):
        queryset = super().get_queryset().filter(author=self.request.user.id)
        return queryset


class QuizCreateView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    CreateView
):
    model = Quiz
    form_class = QuizForm
    template_name = 'quiz/quiz_form.html'
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('users:login')
    title_text = txt.CREATE_QUIZ_TITLE
    btn_text = txt.CREATE_BTN

    def get_success_url(self):
        return reverse_lazy('quiz:quiz_card', kwargs={'quiz_id': self.object.id})

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super().form_valid(form)


class QuizUpdateView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    UserPassesTestMixin,
    UpdateView
):
    model = Quiz
    form_class = QuizForm
    template_name = 'quiz/quiz_form.html'
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('users:login')
    title_text = txt.UPDATE_QUIZ_TITLE
    btn_text = txt.UPDATE_BTN

    def test_func(self):
        return self.request.user == self.get_object().author


class QuizDeleteView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    UserPassesTestMixin,
    DeleteView
):
    model = Quiz
    template_name = "quiz/delete.html"
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('quiz:list_my')
    title_text = txt.DELETE_QUIZ_TITLE
    btn_text = txt.DELETE_BTN

    def test_func(self):
        return self.request.user == self.get_object().author

pollequiz/quiz/templates/quiz/delete.html
{% extends "base.html" %}
{% load i18n %}
{% load bootstrap4 %}

{% block content %}
<main role="main" class="container wrapper flex-grow-1">
    <h1 class="my-4">{{ title }}</h1>
    <p>{% translate "Are you sure you want to delete" %}
        {% if object.first_name %}
            {{ object.first_name }} {{ object.last_name }}?
        {% elif object.username %}
            {{ object.username }}?
        {% elif object.name %}
            {{ object.name }}?
        {% else %}
            "{{ object.text }}"?
        {% endif %}</p>
    <div>
        <form method="post">
            {% csrf_token %}
            {% bootstrap_button button_text button_type="submit" button_class="btn-danger" %}
        </form>
    </div>
    <div class="mt-3">
        <a class="btn btn-secondary" href="{{request.META.HTTP_REFERER}}" role="button">{% trans "Back" %}</a>
    </div>
</main>
{% endblock %}

pollequiz/quiz/templates/quiz/list.html
{% extends 'base.html' %}
{% load i18n bootstrap4 %}

{% block content %}
    <main role="main" class="container wrapper flex-grow-1">
        <h1 class="my-4">{% translate 'All Quizzes and Polls' %}</h1>
        <div class="container">
            <a href="{% url 'quiz:new' %}" class="btn btn-dark">{% translate 'New quiz' %}</a>
        </div>
        <div class="container">
            <form class="form-inline center my-auto" method="get">
                {% csrf_token %}
                {% bootstrap_form filter.form form_group_class="form-group" field_class="ml-2 mr-3 my-3" %}
                {% bootstrap_button button_text button_type="submit"  button_class="btn btn-dark" %}
            </form>
        </div>
        <table class="table table-hover">
            <thead class="table-dark">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">{% translate 'Name' %}</th>
                    <th scope="col">{% translate 'Created by' %}</th>
                    <th scope="col">{% translate 'Type' %}</th>
                    <th scope="col">{% translate 'Created at' %}</th>
                    <th scope="col">{% translate 'Last modified' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for quiz in filter.qs %}
                <tr>
                    <th scope="row">{{quiz.id}}</th>
                    <td><a href="{% url 'quiz:quiz_card' quiz.id %}">{{quiz.name}}</a></td>
                    <td>{{quiz.author}}</td>
                    <td>
                        {% if quiz.is_poll %}
                            {% translate 'Poll' %}
                        {% else %}
                            {% translate 'Quiz' %}
                        {% endif %}
                    </td>
                    <td>{{quiz.created_at}}</td>
                    <td>{{quiz.modified_at}}</td>
                </tr>              
                {% endfor %}
            </tbody> 
        </table>
    </main>
{% endblock %}

pollequiz/quiz/templates/quiz/quiz_answers.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<main role="main" class="container wrapper flex-grow-1">
    <h1 class="my-4">{% translate 'Question details' %}</h1>

    <div class="card">
        <h5 class="card-header"><a href="{% url 'quiz:quiz_card' quiz.id %}">{{quiz.name}}</a></h5>
        <div class="card-body">
          <p>{% translate 'Question' %} {{question.q_number}}</p>
          <p class="card-text">{{question.text}}</p>
          {% if user.id == quiz.author.id %}
          <a href="{% url 'quiz:question_update' quiz.id question.id %}" class="btn btn-dark">{% translate 'Edit' %}</a>
          <a href="{% url 'quiz:question_delete' quiz.id question.id %}" class="btn btn-dark">{% translate 'Delete' %}</a>
          <a href="{% url 'quiz:answer_new' quiz.id question.id %}" class="btn btn-dark">{% translate 'Add answer' %}</a>
          {% endif %}
          {% if objects %}
          <div class="card mt-3">
            <div class="card-body">
              <h5 class="card-title">{% translate 'Answers' %}</h5>
              <table class="table table-sm table-borderless">
                {% for answer in objects %}
                  <tr>
                    <td>{{answer.a_number}}</td>
                    <td>
                      {{answer.text|truncatechars:40}}
                    </td>
                    <td>{% translate 'Correct' %}: {{answer.correct}}</td>
                    <td>
                        <a href="{% url 'quiz:answer_update' quiz.id question.id answer.id %}" class="btn btn-dark">{% translate 'Edit' %}</a>
                        <a href="{% url 'quiz:answer_delete' quiz.id question.id answer.id %}" class="btn btn-dark">{% translate 'Delete' %}</a>
                    </td>
                  </tr>
                {% endfor %}
              </table>
            </div>
          </div>
          {% endif %}
        </div>
    </div>

</main>
{% endblock content %}

pollequiz/quiz/templates/quiz/quiz_form.html
{% extends 'base.html' %}
{% load i18n bootstrap4 %}

{% block content %}
    <main role="main" class="container wrapper flex-grow-1">
        <h1 class="my-4">{{ title }}</h1>
        {% if subtitle %}
        <h5 class="my-4">{{ subtitle }}</h5>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% bootstrap_button button_text button_type="submit"  button_class="btn-dark" %}
        </form>
        <div class="mt-3">
            <a class="btn btn-secondary" href="{{request.META.HTTP_REFERER}}" role="button">{% trans "Back" %}</a>
        </div>
    </main>
{% endblock content %}

pollequiz/quiz/templates/quiz/quiz_questions.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<main role="main" class="container wrapper flex-grow-1">
    <h1 class="my-4">{% translate 'Quiz details' %}</h1>

    <div class="card">
        <h5 class="card-header">{{quiz.name}}</h5>
        <div class="card-body">
          <p class="card-text">{{quiz.description}}</p>
          <p><a href="{% url 'run:takes_list' quiz.id %}" class="btn btn-dark">{% translate 'Quiz takes results' %}</a></p>
          <table class="table table-sm table-borderless">
            <tr>
                <td>{% translate 'Author' %}</td>
                <td>
                  {{quiz.author}}
                  {% if quiz.author.first_name or quiz.author.last_name %}
                    <br/>{{quiz.author.first_name}} {{quiz.author.last_name}}
                  {% endif %}
                </td>
            </tr>
            <tr>
                <td>{% translate 'Created at' %}</td>
                <td>{{quiz.created_at}}</td>
            </tr>
            <tr>
                <td>{% translate 'Last modified' %}</td>
                <td>{{quiz.modified_at}}</td>
            </tr>
          </table>
          {% if user.id == quiz.author.id %}
          <a href="{% url 'quiz:quiz_update' quiz.id %}" class="btn btn-dark">{% translate 'Edit' %}</a>
          <a href="{% url 'quiz:quiz_delete' quiz.id %}" class="btn btn-dark">{% translate 'Delete' %}</a>
          <a href="{% url 'quiz:question_new' quiz.id %}" class="btn btn-dark">{% translate 'Add question' %}</a>
          {% endif %}
          {% if objects %}
          <div class="card mt-3">
            <div class="card-body">
              <h5 class="card-title">{% translate 'Questions' %}</h5>
              <table class="table table-sm table-borderless">
                {% for question in objects %}
                  <tr>
                    <td>{{question.q_number}}</td>
                    <td>
                      <a href="{% url 'quiz:question_card' quiz.id question.id %}">{{question.text|truncatechars:40}}</a>
                    </td>
                    <td>{{question.get_q_type_display}}</td>
                    <td>{% translate 'Points' %}: {{question.points}}</td>
                    <td>
                        <a href="{% url 'quiz:question_update' quiz.id question.id %}" class="btn btn-dark">{% translate 'Edit' %}</a>
                        <a href="{% url 'quiz:question_delete' quiz.id question.id %}" class="btn btn-dark">{% translate 'Delete' %}</a>
                    </td>
                  </tr>
                {% endfor %}
              </table>
            </div>
          </div>
          {% endif %}
        </div>
    </div>

</main>
{% endblock content %}