pollequiz/api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from pollequiz.api import views


app_name = 'api'
urlpatterns = [
    path('', views.QuizListAPIView.as_view(), name='quiz_list'),
    path('auth/', obtain_auth_token, name='token-auth'),
    path('<int:pk>/', views.QuizAPIView.as_view(), name='quiz_detail'),
    path('full/<int:pk>/', views.FullQuizAPIView.as_view(), name='quiz_full'),
]

pollequiz/quiz/urls.py
from django.urls import path
from pollequiz.quiz import views


app_name = 'quiz'
urlpatterns = [
    path('', views.quiz.QuizListView.as_view(), name='list_all'),
    path('my/', views.quiz.MyQuizListView.as_view(), name='list_my'),
    path('<int:quiz_id>/', views.question.QuestionsListView.as_view(), name='quiz_card'),
    path('new/', views.quiz.QuizCreateView.as_view(), name='new'),
    path('<int:pk>/edit/', views.quiz.QuizUpdateView.as_view(), name='quiz_update'),
    path('<int:pk>/delete/', views.quiz.QuizDeleteView.as_view(), name='quiz_delete'),
    path('<int:quiz_id>/new/', views.question.QuestionCreateView.as_view(), name='question_new'),
    path('<int:quiz_id>/<int:pk>/edit/', views.question.QuestionUpdateView.as_view(), name='question_update'),
    path('<int:quiz_id>/<int:pk>/delete/', views.question.QuestionDeleteView.as_view(), name='question_delete'),
    path('<int:quiz_id>/<int:q_id>/', views.answer.AnswerListView.as_view(), name='question_card'),
    path('<int:quiz_id>/<int:q_id>/new/', views.answer.AnswerCreateView.as_view(), name='answer_new'),
    path('<int:quiz_id>/<int:q_id>/<int:pk>/edit/', views.answer.AnswerUpdateView.as_view(), name='answer_update'),
    path('<int:quiz_id>/<int:q_id>/<int:pk>/delete/', views.answer.AnswerDeleteView.as_view(), name='answer_delete'),
]

pollequiz/run/urls.py
from django.urls import path
from pollequiz.run.views import views, auth_views


app_name = 'run'
urlpatterns = [
    path('', views.QuizListView.as_view(), name='quiz_list'),
    path('<int:quiz_id>/', views.TakeFirstPage.as_view(), name='quiz_start'),
    path('<int:quiz_id>/<int:pk>/<int:q_id>', views.TakeQuestion.as_view(), name='quiz_take'),
    path('result/<int:pk>/', views.QuizResult.as_view(), name='quiz_result'),
    path('takes/<int:quiz_id>/', auth_views.ResultsListForAuthors.as_view(), name='takes_list'),
    path('takes/detail/<int:pk>/', auth_views.ResultsForAuthors.as_view(), name='takes_detail'),
]

pollequiz/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, HelpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', HomeView.as_view(), name='home'),
    path('help/', HelpView.as_view(), name='help'),
    path('account/', include('pollequiz.users.urls')),
    path('api/', include('pollequiz.api.urls')),
    path('quiz/', include('pollequiz.quiz.urls')),
    path('test/', include('pollequiz.run.urls')),
]

pollequiz/users/urls.py
from django.urls import path
from pollequiz.users import views


app_name = 'users'
urlpatterns = [
    path('', views.UserLoginView.as_view(), name='login'),
    path('create/', views.UserCreateView.as_view(), name='signup'),
    path('<int:pk>/profile/', views.UserUpdateView.as_view(), name='profile'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
]

pollequiz/quiz/forms.py
from django import forms
from pollequiz.quiz.models import Quiz, Question, Answer


class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = [
            'name',
            'is_poll',
            'description',
        ]


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = [
            'q_number',
            'q_type',
            'text',
            'points',
        ]


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = [
            'a_number',
            'text',
            'correct',
        ]

pollequiz/users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
        ]


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

pollequiz/api/views.py
from rest_framework import generics
from pollequiz.quiz.models import Quiz
from pollequiz.api.serializers import QuizSerializer, FullQuizSerializer


class QuizListAPIView(generics.ListAPIView):
    queryset = Quiz.objects.all()
    serializer_class = QuizSerializer


class QuizAPIView(generics.RetrieveAPIView):
    queryset = Quiz.objects.all()
    serializer_class = QuizSerializer


# class FullQuizAPIView(generics.ListAPIView):
class FullQuizAPIView(generics.RetrieveAPIView):
    queryset = Quiz.objects.all()
    serializer_class = FullQuizSerializer

pollequiz/quiz/views.py
from django.views.generic.detail import DetailView
# from django.views.generic.list import ListView
from django_filters.views import FilterView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from pollequiz.quiz.models import Quiz
from pollequiz.quiz.forms import QuizForm
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
import pollequiz.pq_objects as pq_objects
import pollequiz.text_constants as txt
from .filter import QuizFilter, MyQuizFilter

User = get_user_model()


# Create your views here.
class QuizDetailView(LoginRequiredMixin, DetailView):
    model = Quiz
    template_name = "quiz/quiz_card.html"
    context_object_name = 'quiz'
    redirect_url = reverse_lazy('users:login')


class QuizListView(pq_objects.FailedAccessMixin, pq_objects.PQFormContextMixin, LoginRequiredMixin, FilterView):
    model = Quiz
    filterset_class = QuizFilter
    ordering = ['id']
    redirect_url = reverse_lazy('users:login')
    template_name = 'quiz/list.html'
    context_object_name = 'objects'
    btn_text = txt.FILTER_BTN


class MyQuizListView(QuizListView):
    filterset_class = MyQuizFilter

    def get_queryset(self):
        queryset = super().get_queryset().filter(author=self.request.user.id)
        return queryset


class QuizCreateView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    CreateView
):
    model = Quiz
    form_class = QuizForm
    template_name = 'quiz/quiz_form.html'
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('users:login')
    title_text = txt.CREATE_QUIZ_TITLE
    btn_text = txt.CREATE_BTN

    def get_success_url(self):
        return reverse_lazy('quiz:quiz_card', kwargs={'pk': self.object.id})

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super().form_valid(form)


class QuizUpdateView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    UserPassesTestMixin,
    UpdateView
):
    model = Quiz
    form_class = QuizForm
    template_name = 'quiz/quiz_form.html'
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('users:login')
    title_text = txt.UPDATE_QUIZ_TITLE
    btn_text = txt.UPDATE_BTN

    def test_func(self):
        return self.request.user == self.get_object().author


class QuizDeleteView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    UserPassesTestMixin,
    DeleteView
):
    model = Quiz
    template_name = "quiz/delete.html"
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('quiz:list_my')
    title_text = txt.DELETE_QUIZ_TITLE
    btn_text = txt.DELETE_BTN

    def test_func(self):
        return self.request.user == self.get_object().author

pollequiz/quiz/views/answer.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from pollequiz.quiz.models import Quiz, Question, Answer
from pollequiz.quiz.forms import AnswerForm
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
import pollequiz.pq_objects as pq_objects
import pollequiz.text_constants as txt

User = get_user_model()


class AnswerListView(pq_objects.FailedAccessMixin, pq_objects.PQQuerySetMixin, LoginRequiredMixin, ListView):
    model = Answer
    ordering = ['a_number']
    redirect_url = reverse_lazy('users:login')
    template_name = 'quiz/quiz_answers.html'
    context_object_name = 'objects'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.kwargs.get('quiz_id'):
            context['quiz'] = Quiz.objects.get(id=self.kwargs['quiz_id'])
        if self.kwargs.get('q_id'):
            context['question'] = Question.objects.get(id=self.kwargs['q_id'])
        return context


class AnswerCreateView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    pq_objects.PQSuccessRedirectMixin,
    CreateView
):
    model = Answer
    form_class = AnswerForm
    template_name = 'quiz/quiz_form.html'
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('users:login')
    title_text = txt.CREATE_ANSWER_TITLE
    btn_text = txt.CREATE_BTN

    def form_valid(self, form):
        form.instance.question_id = self.kwargs['q_id']
        return super().form_valid(form)


class AnswerUpdateView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    pq_objects.PQUserTestMixin,
    pq_objects.PQSuccessRedirectMixin,
    UpdateView
):
    model = Answer
    form_class = AnswerForm
    template_name = 'quiz/quiz_form.html'
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('users:login')
    title_text = txt.UPDATE_ANSWER_TITLE
    btn_text = txt.UPDATE_BTN


class AnswerDeleteView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    pq_objects.PQUserTestMixin,
    pq_objects.PQSuccessRedirectMixin,
    DeleteView
):
    model = Answer
    template_name = "quiz/delete.html"
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('quiz:list_my')
    title_text = txt.DELETE_ANSWER_TITLE
    btn_text = txt.DELETE_BTN

pollequiz/quiz/views/question.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from pollequiz.quiz.models import Quiz, Question
from pollequiz.quiz.forms import QuestionForm
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
import pollequiz.pq_objects as pq_objects
import pollequiz.text_constants as txt

User = get_user_model()


class QuestionsListView(pq_objects.FailedAccessMixin, pq_objects.PQQuerySetMixin, LoginRequiredMixin, ListView):
    model = Question
    ordering = ['q_number']
    redirect_url = reverse_lazy('users:login')
    template_name = 'quiz/quiz_questions.html'
    context_object_name = 'objects'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.kwargs.get('quiz_id'):
            context['quiz'] = Quiz.objects.get(id=self.kwargs['quiz_id'])
        return context


class QuestionCreateView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    CreateView
):
    model = Question
    form_class = QuestionForm
    template_name = 'quiz/quiz_form.html'
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('users:login')
    title_text = txt.CREATE_QUESTION_TITLE
    btn_text = txt.CREATE_BTN

    def get_success_url(self):
        return reverse_lazy('quiz:quiz_card', kwargs={'quiz_id': self.object.quiz.id})

    def form_valid(self, form):
        form.instance.quiz_id = self.kwargs['quiz_id']
        return super().form_valid(form)


class QuestionUpdateView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    pq_objects.PQUserTestMixin,
    UpdateView
):
    model = Question
    form_class = QuestionForm
    template_name = 'quiz/quiz_form.html'
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('users:login')
    title_text = txt.UPDATE_QUESTION_TITLE
    btn_text = txt.UPDATE_BTN

    def get_success_url(self):
        return reverse_lazy('quiz:quiz_card', kwargs={'quiz_id': self.object.quiz.id})


class QuestionDeleteView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    pq_objects.PQUserTestMixin,
    DeleteView
):
    model = Question
    template_name = "quiz/delete.html"
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('quiz:list_my')
    title_text = txt.DELETE_QUESTION_TITLE
    btn_text = txt.DELETE_BTN

    def get_success_url(self):
        return reverse_lazy('quiz:quiz_card', kwargs={'quiz_id': self.object.quiz.id})

pollequiz/quiz/views/quiz.py
# from django.views.generic.detail import DetailView
from django_filters.views import FilterView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from pollequiz.quiz.models import Quiz
from pollequiz.quiz.forms import QuizForm
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
import pollequiz.pq_objects as pq_objects
import pollequiz.text_constants as txt
from pollequiz.quiz.filter import QuizFilter, MyQuizFilter

User = get_user_model()


class QuizListView(pq_objects.FailedAccessMixin, pq_objects.PQFormContextMixin, LoginRequiredMixin, FilterView):
    model = Quiz
    filterset_class = QuizFilter
    ordering = ['-modified_at']
    redirect_url = reverse_lazy('users:login')
    template_name = 'quiz/list.html'
    context_object_name = 'objects'
    btn_text = txt.FILTER_BTN


class MyQuizListView(QuizListView):
    filterset_class = MyQuizFilter

    def get_queryset(self):
        queryset = super().get_queryset().filter(author=self.request.user.id)
        return queryset


class QuizCreateView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    CreateView
):
    model = Quiz
    form_class = QuizForm
    template_name = 'quiz/quiz_form.html'
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('users:login')
    title_text = txt.CREATE_QUIZ_TITLE
    btn_text = txt.CREATE_BTN

    def get_success_url(self):
        return reverse_lazy('quiz:quiz_card', kwargs={'quiz_id': self.object.id})

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super().form_valid(form)


class QuizUpdateView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    UserPassesTestMixin,
    UpdateView
):
    model = Quiz
    form_class = QuizForm
    template_name = 'quiz/quiz_form.html'
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('users:login')
    title_text = txt.UPDATE_QUIZ_TITLE
    btn_text = txt.UPDATE_BTN

    def test_func(self):
        return self.request.user == self.get_object().author


class QuizDeleteView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    UserPassesTestMixin,
    DeleteView
):
    model = Quiz
    template_name = "quiz/delete.html"
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('quiz:list_my')
    title_text = txt.DELETE_QUIZ_TITLE
    btn_text = txt.DELETE_BTN

    def test_func(self):
        return self.request.user == self.get_object().author

pollequiz/run/views/auth_views.py
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from pollequiz.run.models import QuizTake, QuizTakeLog
from pollequiz.quiz.models import Quiz
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy

User = get_user_model()


class ResultsListForAuthors(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = QuizTake
    template_name = "run/takes_list.html"
    context_object_name = 'objects'
    redirect_url = reverse_lazy('users:login')

    def get_queryset(self):
        quiz = Quiz.objects.get(id=self.kwargs['quiz_id'])
        qs = super().get_queryset()
        qs = qs.filter(quiz=quiz)
        return qs

    def test_func(self):
        quiz = Quiz.objects.get(id=self.kwargs['quiz_id'])
        return self.request.user == quiz.author


class ResultsForAuthors(TemplateView):
    template_name = "run/take_detail.html"

    def get_context_data(self, **kwargs):
        take = QuizTake.objects.get(id=self.kwargs['pk'])
        quiz = take.quiz
        log = QuizTakeLog.objects.filter(take_id=self.kwargs['pk']).select_related('q_id', 'a_id')
        q_list = quiz.get_questions_list()

        context = super().get_context_data(**kwargs)
        context['take'] = take
        context['q_list'] = q_list
        context['log'] = log
        return context

pollequiz/views.py
from django.views.generic import TemplateView
from django.contrib.auth import get_user_model

User = get_user_model()


class HomeView(TemplateView):

    template_name = "index.html"


class HelpView(TemplateView):

    template_name = "help.html"

pollequiz/templates/base.html
{% load i18n bootstrap4 %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <title>{% translate 'Poll &amp; Quiz' %}</title>
</head>
<body class="d-flex flex-column min-vh-100">
    {% include 'navbar.html' %}

    {% block content %}{% endblock %}
</body>
</html>

pollequiz/templates/form.html
{% extends 'base.html' %}
{% load i18n bootstrap4 %}

{% block content %}
    <main role="main" class="container wrapper flex-grow-1">
        <h1 class="my-4">{{ title }}</h1>
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% bootstrap_button button_text button_type="submit"  button_class="btn-dark" %}
        </form>
    </main>
{% endblock %}

pollequiz/templates/help.html
{% extends 'base.html' %}
{% load i18n static %}

{% block content %}
    <main role="main" class="container wrapper flex-grow-1">
        <h1 class="my-4">{% translate 'Project description' %}</h1>
        <div class="card-body p-5 bg-light mt-5">
            <p>You can take quizzes and see your results in the end. Quiz authors can see the results of all runs for the quizzes they created.</p>
            <p><img src='{% static "pq/img/00_quiz_take.png" %}' width='70%' alt="Quiz run"/></p>
            <p>Create your own quizzes after login: navigate to My quizzes &gt; New quiz.</p>
            <p><img src='{% static "pq/img/01_new_q.png" %}' width='70%' alt="New question"/></p>
            <p><img src='{% static "pq/img/02_quiz_detail.png" %}' width='70%' alt="Quiz details"/></p>
            <p><img src='{% static "pq/img/03_new_a.png" %}' width='70%' alt="Add answers"/></p>
        </div>
    </main>
{% endblock %}

pollequiz/templates/index.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <main role="main" class="container wrapper flex-grow-1">
        <div class="card-body p-5 bg-light mt-5">
            <p>Take a quiz or login to create a new one. See the <a href="{% url 'help' %}">Docs page</a> for details.</p>
            <p><a href="{% url 'api:quiz_list' %}">REST API</a></p>
        </div>
    </main>
{% endblock %}

pollequiz/templates/login.html
{% extends 'base.html' %}
{% load i18n bootstrap4 %}

{% block content %}
    <main role="main" class="container wrapper flex-grow-1">
        <h1 class="my-4">{% translate 'Log in' %}</h1>
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button class="btn btn-dark" type="submit">{% translate 'Log in' %}</button>
            {% endbuttons %}
        </form>
    </main>
{% endblock %}

pollequiz/templates/navbar.html
{% load i18n %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="d-flex container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">{% translate 'Poll &amp; Quiz' %}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="container-fluid flex-grow-1">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'quiz:list_all' %}">{% translate 'All quizzes' %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'quiz:list_my' %}">{% translate 'My quizzes' %}</a>
                    </li>
                    {% endif %}
                    <li>
                        <a class="nav-link active" aria-current="page" href="{% url 'run:quiz_list' %}">{% translate 'Take a quiz' %}</a>
                    </li>
                    <li>
                        <a class="nav-link active" aria-current="page" href="{% url 'help' %}">{% translate 'Docs' %}</a>
                    </li>
                </ul>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:profile' user.id %}">{{ user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">{% translate 'Log out' %}</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'users:login' %}">{% translate 'Log in' %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'users:signup' %}">{% translate 'Sign up' %}</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>