pollequiz/quiz/urls.py
from django.urls import path
from pollequiz.quiz import views


app_name = 'quiz'
urlpatterns = [
    path('', views.quiz.QuizListView.as_view(), name='list_all'),
    path('my/', views.quiz.MyQuizListView.as_view(), name='list_my'),
    path('<int:quiz_id>/', views.question.QuestionsListView.as_view(), name='quiz_card'),
    path('new/', views.quiz.QuizCreateView.as_view(), name='new'),
    path('<int:pk>/edit/', views.quiz.QuizUpdateView.as_view(), name='quiz_update'),
    path('<int:pk>/delete/', views.quiz.QuizDeleteView.as_view(), name='quiz_delete'),
    path('<int:quiz_id>/new/', views.question.QuestionCreateView.as_view(), name='question_new'),
    path('<int:quiz_id>/<int:pk>/edit/', views.question.QuestionUpdateView.as_view(), name='question_update'),
    path('<int:quiz_id>/<int:pk>/delete/', views.question.QuestionDeleteView.as_view(), name='question_delete'),
    path('<int:quiz_id>/<int:q_id>/', views.answer.AnswerListView.as_view(), name='question_card'),
    path('<int:quiz_id>/<int:q_id>/new/', views.answer.AnswerCreateView.as_view(), name='answer_new'),
    path('<int:quiz_id>/<int:q_id>/<int:pk>/edit/', views.answer.AnswerUpdateView.as_view(), name='answer_update'),
    path('<int:quiz_id>/<int:q_id>/<int:pk>/delete/', views.answer.AnswerDeleteView.as_view(), name='answer_delete'),
]

pollequiz/run/urls.py
from django.urls import path
from pollequiz.run.views import views, auth_views


app_name = 'run'
urlpatterns = [
    path('', views.QuizListView.as_view(), name='quiz_list'),
    path('<int:quiz_id>/', views.TakeFirstPage.as_view(), name='quiz_start'),
    path('<int:quiz_id>/<int:pk>/<int:q_id>', views.TakeQuestion.as_view(), name='quiz_take'),
    path('result/<int:pk>/', views.QuizResult.as_view(), name='quiz_result'),
    path('takes/<int:quiz_id>/', auth_views.ResultsListForAuthors.as_view(), name='takes_list'),
    path('takes/detail/<int:pk>/', auth_views.ResultsForAuthors.as_view(), name='takes_detail'),
]

pollequiz/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, HelpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', HomeView.as_view(), name='home'),
    path('help/', HelpView.as_view(), name='help'),
    path('account/', include('pollequiz.users.urls')),
    path('api/', include('pollequiz.api.urls')),
    path('quiz/', include('pollequiz.quiz.urls')),
    path('test/', include('pollequiz.run.urls')),
]

pollequiz/quiz/views/question.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from pollequiz.quiz.models import Quiz, Question
from pollequiz.quiz.forms import QuestionForm
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
import pollequiz.pq_objects as pq_objects
import pollequiz.text_constants as txt

User = get_user_model()


class QuestionsListView(pq_objects.FailedAccessMixin, pq_objects.PQQuerySetMixin, LoginRequiredMixin, ListView):
    model = Question
    ordering = ['q_number']
    redirect_url = reverse_lazy('users:login')
    template_name = 'quiz/quiz_questions.html'
    context_object_name = 'objects'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.kwargs.get('quiz_id'):
            context['quiz'] = Quiz.objects.get(id=self.kwargs['quiz_id'])
        return context


class QuestionCreateView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    CreateView
):
    model = Question
    form_class = QuestionForm
    template_name = 'quiz/quiz_form.html'
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('users:login')
    title_text = txt.CREATE_QUESTION_TITLE
    btn_text = txt.CREATE_BTN

    def get_success_url(self):
        return reverse_lazy('quiz:quiz_card', kwargs={'quiz_id': self.object.quiz.id})

    def form_valid(self, form):
        form.instance.quiz_id = self.kwargs['quiz_id']
        return super().form_valid(form)


class QuestionUpdateView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    pq_objects.PQUserTestMixin,
    UpdateView
):
    model = Question
    form_class = QuestionForm
    template_name = 'quiz/quiz_form.html'
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('users:login')
    title_text = txt.UPDATE_QUESTION_TITLE
    btn_text = txt.UPDATE_BTN

    def get_success_url(self):
        return reverse_lazy('quiz:quiz_card', kwargs={'quiz_id': self.object.quiz.id})


class QuestionDeleteView(
    pq_objects.FailedAccessMixin,
    pq_objects.PQFormContextMixin,
    LoginRequiredMixin,
    pq_objects.PQUserTestMixin,
    DeleteView
):
    model = Question
    template_name = "quiz/delete.html"
    success_url = reverse_lazy('quiz:list_my')
    redirect_url = reverse_lazy('quiz:list_my')
    title_text = txt.DELETE_QUESTION_TITLE
    btn_text = txt.DELETE_BTN

    def get_success_url(self):
        return reverse_lazy('quiz:quiz_card', kwargs={'quiz_id': self.object.quiz.id})

pollequiz/run/views.py
from django_filters.views import FilterView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic import FormView
from pollequiz.run.forms import TakeForm, QuestionForm
from pollequiz.quiz.models import Quiz, Question, Answer
from pollequiz.quiz.filter import QuizFilter
from pollequiz.run.models import QuizTake, QuizTakeLog
from django.http import HttpResponseRedirect
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
import pollequiz.pq_objects as pq_objects
import pollequiz.text_constants as txt

User = get_user_model()


class QuizListView(pq_objects.PQFormContextMixin, FilterView):
    model = Quiz
    filterset_class = QuizFilter
    template_name = 'run/quiz_list.html'
    ordering = ['-modified_at']
    context_object_name = 'objects'
    btn_text = txt.FILTER_BTN


class TakeFirstPage(pq_objects.PQFormContextMixin, CreateView):
    model = QuizTake
    form_class = TakeForm
    template_name = 'quiz/quiz_form.html'
    success_url = reverse_lazy
    title = txt.TAKE_QUIZ_TITLE
    btn_text = txt.TAKE_QUIZ_BTN

    def get_success_url(self):
        quiz_id = self.object.quiz.id
        first_q_id = Question.objects.filter(quiz=quiz_id).order_by('q_number', 'id').first().id
        return reverse_lazy('run:quiz_take', kwargs={'quiz_id': quiz_id, 'pk': self.object.id, 'q_id': first_q_id})

    def get_initial(self):
        if self.request.user:
            uname = ' '.join((self.request.user.first_name, self.request.user.last_name))
            uname = uname.strip()
            if not uname:
                uname = self.request.user.username
        return {'taker_name': uname}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subtitle'] = Quiz.objects.get(id=self.kwargs['quiz_id']).name
        return context

    def form_valid(self, form):
        form.instance.quiz = Quiz.objects.get(id=self.kwargs['quiz_id'])
        return super().form_valid(form)


class TakeQuestion(FormView):
    form_class = QuestionForm
    template_name = 'run/question.html'

    def get_form(self, form_class=QuestionForm):
        q_id = self.kwargs.get('q_id')
        if q_id:
            self.question = Question.objects.get(id=q_id)
        return form_class(**self.get_form_kwargs())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        question = Question.objects.get(id=self.kwargs['q_id'])
        context['question'] = question
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        return dict(kwargs, question=self.question)

    def get_success_url(self):
        quiz = Quiz.objects.get(id=self.kwargs['quiz_id'])
        q_list = list(Question.objects.values('id').filter(quiz=quiz.id).order_by('q_number', 'id'))
        q_list = [q['id'] for q in q_list]
        curr_id = self.kwargs.get('q_id')
        curr_index = q_list.index(curr_id)
        if curr_index + 1 >= len(q_list):
            url = reverse_lazy('run:quiz_result', kwargs={'pk': self.kwargs['pk']})
        else:
            next = q_list[curr_index + 1]
            url = reverse_lazy('run:quiz_take', kwargs={'quiz_id': quiz.id, 'pk': self.kwargs['pk'], 'q_id': next})
        return url

    def form_valid(self, form):
        log_entry = QuizTakeLog()
        log_entry.take_id = QuizTake.objects.get(id=self.kwargs.get('pk'))
        log_entry.q_id = self.question
        log_entry.a_id = Answer.objects.get(id=form.data.get('answers'))
        log_entry.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        answer_list = form.data.getlist('answers')
        if answer_list:
            for ans in answer_list:
                log_entry = QuizTakeLog()
                log_entry.take_id = QuizTake.objects.get(id=self.kwargs.get('pk'))
                log_entry.q_id = self.question
                log_entry.a_id = Answer.objects.get(id=ans)
                log_entry.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return super().form_invalid(form)


class QuizResult(ListView):
    model = QuizTakeLog
    template_name = 'run/results.html'
    context_object_name = 'objects'

    def get_queryset(self):
        queryset = QuizTakeLog.objects.filter(take_id=self.kwargs['pk']).select_related('q_id', 'a_id')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        results = self.get_queryset()
        answer_set = [entry.a_id for entry in list(results)]
        quiz_take = QuizTake.objects.get(id=self.kwargs['pk'])
        quiz = Quiz.objects.get(id=quiz_take.quiz.id)
        q_list = quiz.get_questions_list()
        total_points = 0
        correct = 0
        for qu in q_list:
            is_correct = True
            a_list = qu.get_answers_list()
            for a in a_list:
                if a.correct and a not in answer_set:
                    is_correct = False
                    break
                if not a.correct and a in answer_set:
                    is_correct = False
                    break
            if is_correct:
                correct += 1
                total_points += qu.points
        context['total_points'] = total_points
        context['correct'] = correct
        context['incorrect'] = len(q_list) - correct

        return context

pollequiz/run/views/auth_views.py
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from pollequiz.run.models import QuizTake, QuizTakeLog
from pollequiz.quiz.models import Quiz
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy

User = get_user_model()


class ResultsListForAuthors(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = QuizTake
    template_name = "run/takes_list.html"
    context_object_name = 'objects'
    redirect_url = reverse_lazy('users:login')

    def get_queryset(self):
        quiz = Quiz.objects.get(id=self.kwargs['quiz_id'])
        qs = super().get_queryset()
        qs = qs.filter(quiz=quiz)
        return qs

    def test_func(self):
        quiz = Quiz.objects.get(id=self.kwargs['quiz_id'])
        return self.request.user == quiz.author


class ResultsForAuthors(TemplateView):
    template_name = "run/take_detail.html"

    def get_context_data(self, **kwargs):
        take = QuizTake.objects.get(id=self.kwargs['pk'])
        quiz = take.quiz
        log = QuizTakeLog.objects.filter(take_id=self.kwargs['pk']).select_related('q_id', 'a_id')
        q_list = quiz.get_questions_list()

        context = super().get_context_data(**kwargs)
        context['take'] = take
        context['q_list'] = q_list
        context['log'] = log
        return context

pollequiz/run/views/views.py
from django_filters.views import FilterView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic import FormView
from pollequiz.run.forms import TakeForm, QuestionForm
from pollequiz.quiz.models import Quiz, Question, Answer
from pollequiz.quiz.filter import QuizFilter
from pollequiz.run.models import QuizTake, QuizTakeLog
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
import pollequiz.pq_objects as pq_objects
import pollequiz.text_constants as txt


class QuizListView(pq_objects.PQFormContextMixin, FilterView):
    model = Quiz
    filterset_class = QuizFilter
    template_name = 'run/quiz_list.html'
    ordering = ['-modified_at']
    context_object_name = 'objects'
    btn_text = txt.FILTER_BTN


class TakeFirstPage(pq_objects.PQFormContextMixin, CreateView):
    model = QuizTake
    form_class = TakeForm
    template_name = 'quiz/quiz_form.html'
    success_url = reverse_lazy('run:quiz_list')
    title = txt.TAKE_QUIZ_TITLE
    btn_text = txt.TAKE_QUIZ_BTN

    def get_success_url(self):
        quiz_id = self.object.quiz.id
        first_q_id = Question.objects.filter(quiz=quiz_id).order_by('q_number', 'id').first().id
        return reverse_lazy('run:quiz_take', kwargs={'quiz_id': quiz_id, 'pk': self.object.id, 'q_id': first_q_id})

    def get_initial(self):
        uname = ''
        if self.request.user.is_authenticated:
            uname = ' '.join((self.request.user.first_name, self.request.user.last_name))
            uname = uname.strip()
            if not uname:
                uname = self.request.user.username
        return {'taker_name': uname}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subtitle'] = Quiz.objects.get(id=self.kwargs['quiz_id']).name
        return context

    def form_valid(self, form):
        form.instance.quiz = Quiz.objects.get(id=self.kwargs['quiz_id'])
        return super().form_valid(form)


class TakeQuestion(FormView):
    form_class = QuestionForm
    template_name = 'run/question.html'

    def get_form(self, form_class=QuestionForm):
        q_id = self.kwargs.get('q_id')
        if q_id:
            self.question = Question.objects.get(id=q_id)
        return form_class(**self.get_form_kwargs())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        question = Question.objects.get(id=self.kwargs['q_id'])
        context['question'] = question
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        return dict(kwargs, question=self.question)

    def get_success_url(self):
        quiz = Quiz.objects.get(id=self.kwargs['quiz_id'])
        q_list = list(Question.objects.values('id').filter(quiz=quiz.id).order_by('q_number', 'id'))
        q_list = [q['id'] for q in q_list]
        curr_id = self.kwargs.get('q_id')
        curr_index = q_list.index(curr_id)
        if curr_index + 1 >= len(q_list):
            url = reverse_lazy('run:quiz_result', kwargs={'pk': self.kwargs['pk']})
        else:
            next = q_list[curr_index + 1]
            url = reverse_lazy('run:quiz_take', kwargs={'quiz_id': quiz.id, 'pk': self.kwargs['pk'], 'q_id': next})
        return url

    def form_valid(self, form):
        log_entry = QuizTakeLog()
        log_entry.take_id = QuizTake.objects.get(id=self.kwargs.get('pk'))
        log_entry.q_id = self.question
        log_entry.a_id = Answer.objects.get(id=form.data.get('answers'))
        log_entry.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        answer_list = form.data.getlist('answers')
        if answer_list:
            for ans in answer_list:
                log_entry = QuizTakeLog()
                log_entry.take_id = QuizTake.objects.get(id=self.kwargs.get('pk'))
                log_entry.q_id = self.question
                log_entry.a_id = Answer.objects.get(id=ans)
                log_entry.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return super().form_invalid(form)


class QuizResult(ListView):
    model = QuizTakeLog
    template_name = 'run/results.html'
    context_object_name = 'objects'

    def get_queryset(self):
        queryset = QuizTakeLog.objects.filter(take_id=self.kwargs['pk']).select_related('q_id', 'a_id')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        results = self.get_queryset()
        answer_set = [entry.a_id for entry in list(results)]
        quiz_take = QuizTake.objects.get(id=self.kwargs['pk'])
        quiz = Quiz.objects.get(id=quiz_take.quiz.id)
        q_list = quiz.get_questions_list()
        total_points = 0
        correct = 0
        for qu in q_list:
            is_correct = True
            a_list = qu.get_answers_list()
            for a in a_list:
                if a.correct and a not in answer_set:
                    is_correct = False
                    break
                if not a.correct and a in answer_set:
                    is_correct = False
                    break
            if is_correct:
                correct += 1
                total_points += qu.points
        context['total_points'] = total_points
        context['correct'] = correct
        context['incorrect'] = len(q_list) - correct

        return context

pollequiz/run/templates/run/question.html
{% extends 'base.html' %}
{% load i18n bootstrap4 %}

{% block content %}
    <main role="main" class="container wrapper flex-grow-1">

      <p class="lead">{{ question.text }}</p>  
        <form action="" method="POST">{% csrf_token %}
          <input type=hidden name="question_id" value="{{ question.id }}">
            <ul class="list-group">

              {% for answer in form.answers %}
                <li class="list-group-item">
                  {{ answer }}
                </li>
              {% endfor %}
          
            </ul>
              <input type="submit" value={% trans "Submit" %} class="btn btn-warning mt-3" >
        </form>

    </main>
{% endblock %}

pollequiz/run/templates/run/quiz_list.html
{% extends 'base.html' %}
{% load i18n bootstrap4 %}

{% block content %}
    <main role="main" class="container wrapper flex-grow-1">
        <h1 class="my-4">{% translate 'All Quizzes and Polls' %}</h1>
        <div class="container">
            <form class="form-inline center my-auto" method="get">
                {% csrf_token %}
                {% bootstrap_form filter.form form_group_class="form-group" field_class="ml-2 mr-3 my-3" %}
                {% bootstrap_button button_text button_type="submit"  button_class="btn btn-dark" %}
            </form>
        </div>
        <table class="table table-hover">
            <thead class="table-dark">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">{% translate 'Name' %}</th>
                    <th scope="col">{% translate 'Created by' %}</th>
                    <th scope="col">{% translate 'Type' %}</th>
                    <th scope="col">{% translate 'Created at' %}</th>
                    <th scope="col">{% translate 'Last modified' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for quiz in filter.qs %}
                <tr>
                    <th scope="row">{{quiz.id}}</th>
                    <td><a href="{% url 'run:quiz_start' quiz.id %}">{{quiz.name}}</a></td>
                    <td>{{quiz.author}}</td>
                    <td>
                        {% if quiz.is_poll %}
                            {% translate 'Poll' %}
                        {% else %}
                            {% translate 'Quiz' %}
                        {% endif %}
                    </td>
                    <td>{{quiz.created_at}}</td>
                    <td>{{quiz.modified_at}}</td>
                </tr>              
                {% endfor %}
            </tbody> 
        </table>
    </main>
{% endblock %}

pollequiz/run/templates/run/results.html
{% extends 'base.html' %}
{% load i18n bootstrap4 %}

{% block content %}
<main role="main" class="container wrapper flex-grow-1">
    {% comment %} {{ objects }}
    {% for obj in objects %}
    <p>{{ obj.q_id.text }} {{ obj.a_id.text }}</p>
    {% endfor %} {% endcomment %}
    <h5>{% translate 'Your results:' %}</h5>
    <p>{% translate 'Answered correctly:' %} {{ correct }}</p>
    <p>{% translate 'Answered incorrectly:' %} {{ incorrect }}</p>
    <p>{% translate 'Points earned:' %} {{ total_points }}</p>
</main>
{% endblock %}

pollequiz/run/templates/run/take_detail.html
{% extends 'base.html' %}
{% load i18n bootstrap4 %}

{% block content %}
    <main role="main" class="container wrapper flex-grow-1">
        <h1 class="my-4">{% translate 'Quiz takes' %}</h1>
        
        
        
        <div class="card">
            <h5 class="card-header">{{take.quiz.name}}</h5>
            <div class="card-body">
              <p class="card-text">ID: {{take.id}}, {% translate 'Taker name' %}: <b>{{take.taker_name}}</b></p>
              <p class="card-text">{{take.quiz_date}}</p>

              <div class="card mt-3">
                <div class="card-body">
                  <h5 class="card-title">{% translate 'Answers' %}</h5>
                  <table class="table table-sm table-borderless">
                    {% for qu in q_list %}
                    <tr>
                        <td>{{qu.q_number}}</td>
                        <td>{{qu.text}}</td>
                        <td>
                            {% for entry in log %}
                                {% if entry.q_id == qu %}
                                <p>{{ entry.a_id.a_number }}. {{ entry.a_id.text }}</p>
                                {% endif %}
                            {% endfor %}
                        </td>
                    </tr>
                    {% endfor %}
                  </table>
                </div>
              </div>
            </div>
        </div>
    </main>
{% endblock %}

pollequiz/run/templates/run/takes_list.html
{% extends 'base.html' %}
{% load i18n bootstrap4 %}

{% block content %}
    <main role="main" class="container wrapper flex-grow-1">
        <h1 class="my-4">{% translate 'Quiz takes' %}</h1>
        <table class="table table-hover">
            <thead class="table-dark">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">{% translate 'Quiz' %}</th>
                    <th scope="col">{% translate 'Taker name' %}</th>
                    <th scope="col">{% translate 'Quiz date' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for take in objects %}
                <tr>
                    <th scope="row"><a href="{% url 'run:takes_detail' take.id %}">{{take.id}}</a></th>
                    <td><a href="{% url 'quiz:quiz_card' take.quiz.id %}">{{take.quiz.name}}</a></td>
                    <td>{{take.taker_name}}</td>
                    <td>{{take.quiz_date}}</td>
                </tr>              
                {% endfor %}
            </tbody> 
        </table>
    </main>
{% endblock %}